version: '3.7'
services:
  dncsrv:
    build: .
    image: dncontrolsrv
    container_name: dncsrv
    ports:
      - "11037:11037"
  bd:
    image: mariadb
    container_name: bd
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: dncontrol
      MYSQL_USER: dnc
      MYSQL_PASSWORD: dam205
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
      - ./sql/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_volume: