version: '3.7'
services:
  srv:
    build: .
    image: dncontrolsrv
    container_name: dncsrv
    expose:
      - "11037:11037"
    networks:
      - backend
  bd:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dncontrol
      MYSQL_USER: dnc
      MYSQL_PASSWORD: dam205
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
     - db_volume:/var/lib/mysql
networks:
  backend:
    driver: bridge
volumes:
  db_volume: