/*
Created: 01/10/2023
Modified: 19/10/2023
Model: DnControl
Database: Oracle 11g Release 2
*/


-- Create tables section -------------------------------------------------

-- Table PERSONAJE

CREATE TABLE "PERSONAJE"(
  "PERSONAJE_ID" Number(4,0) NOT NULL,
  "USUARIO_ID" Number(3,0),
  "NOMBRE_PERSONAJE" Varchar2(50 ) NOT NULL,
  "APELLIDO" Varchar2(100 ),
  "TRANSFONDO" Varchar2(4000 ) NOT NULL,
  "FUERZA" Number(2,0) NOT NULL,
  "DESTREZA" Number(2,0) NOT NULL,
  "CONSTITUCION" Number(2,0) NOT NULL,
  "INTELIGENCIA" Number(2,0) NOT NULL,
  "SABIDURIA" Number(2,0) NOT NULL,
  "CARISMA" Number(2,0) NOT NULL,
  "JUGADOR" Char(1 ) NOT NULL,
  CONSTRAINT "CHECK_FUERZA" CHECK (FUERZA between 1 and 50),
  CONSTRAINT "CHECK_DESTREZA" CHECK (DESTREZA between 1 and 50),
  CONSTRAINT "CHECK_CONSTITUCION" CHECK (CONSTITUCION between 1 and 50),
  CONSTRAINT "CHECK_INTELIGENCIA" CHECK (INTELIGENCIA between 1 and 50),
  CONSTRAINT "CHECK_SABIDURIA" CHECK (SABIDURIA between 1 and 50),
  CONSTRAINT "CHECK_CARISMA" CHECK (CARISMA between 1 and 50),
  CONSTRAINT "CHECK_JUGADOR" CHECK (JUGADOR in('j','e'))
)
/

-- Create indexes for table PERSONAJE

CREATE INDEX "IX_Relationship5" ON "PERSONAJE" ("USUARIO_ID")
/

-- Add keys for table PERSONAJE

ALTER TABLE "PERSONAJE" ADD CONSTRAINT "Key1" PRIMARY KEY ("PERSONAJE_ID")
/

ALTER TABLE "PERSONAJE" ADD CONSTRAINT "NOMBRE_PERSONAJE" UNIQUE ("NOMBRE_PERSONAJE")
/

-- Table HABILIDAD

CREATE TABLE "HABILIDAD"(
  "HABILIDAD_ID" Number(4,0) NOT NULL,
  "NUM_DADO_ID" Number(1,0),
  "NOMBRE_HABILIDAD" Varchar2(50 ) NOT NULL,
  "DESCRIPCION" Varchar2(1000 ) NOT NULL,
  "CANTIDAD_DADO" Number(3,0) NOT NULL
)
/

-- Create indexes for table HABILIDAD

CREATE INDEX "IX_Relationship3" ON "HABILIDAD" ("NUM_DADO_ID")
/

-- Add keys for table HABILIDAD

ALTER TABLE "HABILIDAD" ADD CONSTRAINT "Key2" PRIMARY KEY ("HABILIDAD_ID")
/

ALTER TABLE "HABILIDAD" ADD CONSTRAINT "NOMBRE_HABILIDAD" UNIQUE ("NOMBRE_HABILIDAD")
/

ALTER TABLE "HABILIDAD" ADD CONSTRAINT "DESCRIPCION" UNIQUE ("DESCRIPCION")
/

-- Table PERSONAJE_HABILIDAD

CREATE TABLE "PERSONAJE_HABILIDAD"(
  "PERSONAJE_ID" Number(4,0) NOT NULL,
  "HABILIDAD_ID" Number(4,0) NOT NULL
)
/

-- Add keys for table PERSONAJE_HABILIDAD

ALTER TABLE "PERSONAJE_HABILIDAD" ADD CONSTRAINT "Key3" PRIMARY KEY ("PERSONAJE_ID","HABILIDAD_ID")
/

-- Table USUARIO

CREATE TABLE "USUARIO"(
  "USUARIO_ID" Number(3,0) NOT NULL,
  "EMAIL" Varchar2(100 ) NOT NULL,
  "NOMBRE_USUARIO" Varchar2(50 ) NOT NULL,
  "PASSWD" Char(64 ) NOT NULL,
  CONSTRAINT "CHECK_EMAIL" CHECK (EMAIL LIKE '%@%.%')
)
/

-- Add keys for table USUARIO

ALTER TABLE "USUARIO" ADD CONSTRAINT "Key4" PRIMARY KEY ("USUARIO_ID")
/

ALTER TABLE "USUARIO" ADD CONSTRAINT "NOMBRE_USUARIO" UNIQUE ("NOMBRE_USUARIO")
/

ALTER TABLE "USUARIO" ADD CONSTRAINT "EMAIL" UNIQUE ("EMAIL")
/

-- Table OBJETO

CREATE TABLE "OBJETO"(
  "OBJETO_ID" Number(4,0) NOT NULL,
  "PERSONAJE_ID" Number(4,0),
  "NOMBRE_OBJETO" Varchar2(100 ) NOT NULL,
  "DESCRIPCION" Varchar2(1000 ) NOT NULL,
  "VALOR" Number(5,0) NOT NULL
)
/

-- Create indexes for table OBJETO

CREATE INDEX "IX_Relationship4" ON "OBJETO" ("PERSONAJE_ID")
/

-- Add keys for table OBJETO

ALTER TABLE "OBJETO" ADD CONSTRAINT "Key5" PRIMARY KEY ("OBJETO_ID")
/

-- Table SEL_NUM_DADO

CREATE TABLE "SEL_NUM_DADO"(
  "NUM_DADO_ID" Number(2,0) NOT NULL,
  "NUM_DADO" Number(3,0) NOT NULL
)
/

-- Add keys for table SEL_NUM_DADO

ALTER TABLE "SEL_NUM_DADO" ADD CONSTRAINT "Key6" PRIMARY KEY ("NUM_DADO_ID")
/



-- Create foreign keys (relationships) section ------------------------------------------------- 

ALTER TABLE "PERSONAJE_HABILIDAD" ADD CONSTRAINT "Relationship1" FOREIGN KEY ("PERSONAJE_ID") REFERENCES "PERSONAJE" ("PERSONAJE_ID")
/


ALTER TABLE "PERSONAJE_HABILIDAD" ADD CONSTRAINT "Relationship2" FOREIGN KEY ("HABILIDAD_ID") REFERENCES "HABILIDAD" ("HABILIDAD_ID")
/


ALTER TABLE "HABILIDAD" ADD CONSTRAINT "Relationship3" FOREIGN KEY ("NUM_DADO_ID") REFERENCES "SEL_NUM_DADO" ("NUM_DADO_ID")
/


ALTER TABLE "OBJETO" ADD CONSTRAINT "Relationship4" FOREIGN KEY ("PERSONAJE_ID") REFERENCES "PERSONAJE" ("PERSONAJE_ID")
/


ALTER TABLE "PERSONAJE" ADD CONSTRAINT "Relationship5" FOREIGN KEY ("USUARIO_ID") REFERENCES "USUARIO" ("USUARIO_ID")
/

--------------------------------------------------------
--  DDL for Sequence SEC_PERSONAJE
--------------------------------------------------------

   CREATE SEQUENCE  SEC_PERSONAJE  MINVALUE 0 MAXVALUE 9999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;
   
--------------------------------------------------------
--  DDL for Sequence SEC_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  SEC_USUARIO  MINVALUE 0 MAXVALUE 999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence SEC_OBJETOS
--------------------------------------------------------

   CREATE SEQUENCE  SEC_OBJETO  MINVALUE 0 MAXVALUE 9999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence SEC_HABILIDAD
--------------------------------------------------------

   CREATE SEQUENCE  SEC_HABILIDAD  MINVALUE 0 MAXVALUE 9999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence SEC_SEL_NUM_DADO
--------------------------------------------------------

   CREATE SEQUENCE  "DNCONTROL"."SEC_SEL_NUM_DADO"  MINVALUE 0 MAXVALUE 99 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Procedure INSERTAR_PERSONAJE
--------------------------------------------------------

  CREATE OR REPLACE PROCEDURE INSERTAR_PERSONAJE
(
  USR_ID USUARIO.USUARIO_ID%TYPE,
  NOM_PER PERSONAJE.NOMBRE_PERSONAJE%TYPE,
  APP_PER PERSONAJE.APELLIDO%TYPE,
  TRF_PER PERSONAJE.TRANSFONDO%TYPE,
  FUE_PER PERSONAJE.FUERZA%TYPE,
  DES_PER PERSONAJE.DESTREZA%TYPE,
  CON_PER PERSONAJE.CONSTITUCION%TYPE,
  INT_PER PERSONAJE.INTELIGENCIA%TYPE,
  SAB_PER PERSONAJE.SABIDURIA%TYPE,
  CAR_PER PERSONAJE.CARISMA%TYPE,
  JUG_PER PERSONAJE.JUGADOR%TYPE
) AS

BEGIN
  INSERT INTO PERSONAJE (PERSONAJE_ID, USUARIO_ID, NOMBRE_PERSONAJE, APELLIDO, TRANSFONDO, FUERZA, DESTREZA, CONSTITUCION, INTELIGENCIA, SABIDURIA, CARISMA, JUGADOR)
    VALUES (SEC_PERSONAJE.NEXTVAL, USR_ID, NOM_PER, APP_PER, TRF_PER, FUE_PER, DES_PER, CON_PER, INT_PER, SAB_PER, CAR_PER, JUG_PER);
END INSERTAR_PERSONAJE;

/
