/*
Created: 01/10/2023
Modified: 19/10/2023
Model: DnControl
Database: Oracle 11g Release 2
*/


-- Drop relationships section -------------------------------------------------

ALTER TABLE "PERSONAJE" DROP CONSTRAINT "Relationship5"
/
ALTER TABLE "OBJETO" DROP CONSTRAINT "Relationship4"
/
ALTER TABLE "HABILIDAD" DROP CONSTRAINT "Relationship3"
/
ALTER TABLE "PERSONAJE_HABILIDAD" DROP CONSTRAINT "Relationship2"
/
ALTER TABLE "PERSONAJE_HABILIDAD" DROP CONSTRAINT "Relationship1"
/




-- Drop keys for tables section -------------------------------------------------

ALTER TABLE "SEL_NUM_DADO" DROP CONSTRAINT "Key6"
/
ALTER TABLE "OBJETO" DROP CONSTRAINT "Key5"
/
ALTER TABLE "USUARIO" DROP CONSTRAINT "Key4"
/
ALTER TABLE "USUARIO" DROP CONSTRAINT "NOMBRE_USUARIO"
/
ALTER TABLE "USUARIO" DROP CONSTRAINT "EMAIL"
/
ALTER TABLE "PERSONAJE_HABILIDAD" DROP CONSTRAINT "Key3"
/
ALTER TABLE "HABILIDAD" DROP CONSTRAINT "Key2"
/
ALTER TABLE "HABILIDAD" DROP CONSTRAINT "NOMBRE_HABILIDAD"
/
ALTER TABLE "HABILIDAD" DROP CONSTRAINT "DESCRIPCION"
/
ALTER TABLE "PERSONAJE" DROP CONSTRAINT "Key1"
/
ALTER TABLE "PERSONAJE" DROP CONSTRAINT "NOMBRE_PERSONAJE"
/


-- Drop indexes section -------------------------------------------------

DROP INDEX "IX_Relationship4"
/
DROP INDEX "IX_Relationship3"
/
DROP INDEX "IX_Relationship5"
/


-- Drop tables section ---------------------------------------------------

DROP TABLE "SEL_NUM_DADO"
/
DROP TABLE "OBJETO"
/
DROP TABLE "USUARIO"
/
DROP TABLE "PERSONAJE_HABILIDAD"
/
DROP TABLE "HABILIDAD"
/
DROP TABLE "PERSONAJE"
/

DROP SEQUENCE SEC_USUARIO;
DROP SEQUENCE SEC_PERSONAJE;
DROP SEQUENCE SEC_HABILIDAD;
DROP SEQUENCE SEC_OBJETO;
DROP SECUENCE SEC_SEL_NUM_DADO;

DROP PROCEDURE INSERTAR_PERSONAJE