package dnc.pojospersonajes;

/**
 *
 * @author Admin
 */
public enum ErrorUsuario {
    DEFAULT,
    USUARIO_UNIKE,
    USUARIO_NOTNULL,
    USUARIO_CHECK,
    USUARIO_FK,
    PERSONAJE_UNIKE,
    PERSONAJE_NOTNULL,
    PERSONAJE_CHECK,
    PERSONAJE_FK_USUARIO,
    PERSONAJE_FK,
    OBJETO_NOTNULL,
    OBJETO_FK_PERSONAJE,
    HABILIDAD_UNIKE,
    HABILIDAD_NOTNULL,
    HABILIDAD_FK,
    HABILIDAD_FK_PERSONAJE,
    SELNUMDADO_NOTNULL,
    SELNUMDADO_FK_HABILIDAD,
    PERSONAJE_HABILIDAD_UNIKE,
    PERSONAJE_HABILIDAD_NOTNULL,
    PERSONAJE_HABILIDAD_FK
}
