package dnc.pojospersonajes;

/**
 * Enumeracion con la lista de las operaciones disponibles para las peticiones
 *
 * @author Jose Ramon Bravo
 */
public enum Operaciones {
    INSERTAR_USUARIO,
    ELIMINAR_USUARIO,
    MODIFICAR_USUARIO,
    LEER_USUARIO,
    INSERTAR_PERSONAJE,
    ELIMINAR_PERSONAJE,
    MODIFICAR_PERSONAJE,
    LEER_PERSONAJE,
    LEER_PERSONAJE_JUGADOR,
    LEER_ENEMIGOS,
    INSERTAR_OBJETO,
    ELIMINAR_OBJETO,
    MODIFICAR_OBJETO,
    LEER_OBJETO,
    LEER_OBJETO_PERSONAJE,
    INSERTAR_HABILIDAD,
    ELIMINAR_HABILIDAD,
    MODIFICAR_HABILIDAD,
    LEER_HABILIDAD,
    INSERTAR_PERSONAJE_HABILIDAD,
    ELIMINAR_PERSONAJE_HABILIDAD,
    MODIFICAR_PERSONAJE_HABILIDAD,
    LEER_PERSONAJE_HABILIDAD,
    INSERTAR_SEL_NUM_DADO,
    ELIMINAR_SEL_NUM_DADO,
    MODIFICAR_SEL_NUM_DADO,
    LEER_SEL_NUM_DADO,
    VALIDAR_CONEXION
}
