CREATE DATABASE IF NOT EXISTS DNCONTROL;
USE DNCONTROL;

-- Create tables section -------------------------------------------------

-- Table PERSONAJE

CREATE TABLE IF NOT EXISTS PERSONAJE(
  PERSONAJE_ID INT(4) NOT NULL AUTO_INCREMENT,
  USUARIO_ID INT(3),
  NOMBRE_PERSONAJE VARCHAR(50) NOT NULL UNIQUE,
  APELLIDO VARCHAR(100),
  TRANSFONDO TEXT NOT NULL,
  FUERZA INT(2) NOT NULL CHECK (FUERZA between 1 and 50),
  DESTREZA INT(2) NOT NULL CHECK (DESTREZA between 1 and 50),
  CONSTITUCION INT(2) NOT NULL CHECK (CONSTITUCION between 1 and 50),
  INTELIGENCIA INT(2) NOT NULL CHECK (INTELIGENCIA between 1 and 50),
  SABIDURIA INT(2) NOT NULL CHECK (SABIDURIA between 1 and 50),
  CARISMA INT(2) NOT NULL CHECK (CARISMA between 1 and 50),
  JUGADOR Char(1 ) NOT NULL CHECK (JUGADOR in('j','e')),
  PRIMARY KEY (PERSONAJE_ID)
);

-- Create indexes for table PERSONAJE

CREATE INDEX IX_Relationship5 ON PERSONAJE (USUARIO_ID);

-- Table HABILIDAD

CREATE TABLE IF NOT EXISTS HABILIDAD(
  HABILIDAD_ID INT(4) NOT NULL AUTO_INCREMENT,
  NUM_DADO_ID INT(1),
  NOMBRE_HABILIDAD VARCHAR(50) NOT NULL UNIQUE,
  DESCRIPCION VARCHAR(1000) NOT NULL,
  CANTIDAD_DADO INT(3) NOT NULL,
  PRIMARY KEY (HABILIDAD_ID)
);

-- Create indexes for table HABILIDAD

CREATE INDEX IX_Relationship3 ON HABILIDAD (NUM_DADO_ID);


-- Table PERSONAJE_HABILIDAD

CREATE TABLE IF NOT EXISTS PERSONAJE_HABILIDAD(
  PERSONAJE_ID INT(4) NOT NULL,
  HABILIDAD_ID INT(4) NOT NULL,
  PRIMARY KEY (PERSONAJE_ID,HABILIDAD_ID)
);


-- Table USUARIO

CREATE TABLE IF NOT EXISTS USUARIO(
  USUARIO_ID INT(3) NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(100) NOT NULL UNIQUE CHECK (EMAIL LIKE '%@%.%'),
  NOMBRE_USUARIO VARCHAR(50) NOT NULL UNIQUE,
  PASSWD Char(64) NOT NULL,
  DM BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (USUARIO_ID)
);

-- Table OBJETO

CREATE TABLE IF NOT EXISTS OBJETO(
  OBJETO_ID INT(4) NOT NULL AUTO_INCREMENT,
  PERSONAJE_ID INT(4),
  NOMBRE_OBJETO VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(1000) NOT NULL,
  VALOR INT(5) NOT NULL,
  PRIMARY KEY (OBJETO_ID)
);

-- Create indexes for table OBJETO

CREATE INDEX IX_Relationship4 ON OBJETO (PERSONAJE_ID);

-- Table SEL_NUM_DADO

CREATE TABLE IF NOT EXISTS SEL_NUM_DADO(
  NUM_DADO_ID INT(2) NOT NULL AUTO_INCREMENT,
  NUM_DADO INT(3) NOT NULL,
  PRIMARY KEY (NUM_DADO_ID)
);

-- Create foreign keys (relationships) section ------------------------------------------------- 

ALTER TABLE PERSONAJE_HABILIDAD ADD CONSTRAINT Relationship1 FOREIGN KEY (PERSONAJE_ID) REFERENCES PERSONAJE (PERSONAJE_ID);


ALTER TABLE PERSONAJE_HABILIDAD ADD CONSTRAINT Relationship2 FOREIGN KEY (HABILIDAD_ID) REFERENCES HABILIDAD (HABILIDAD_ID);


ALTER TABLE HABILIDAD ADD CONSTRAINT Relationship3 FOREIGN KEY (NUM_DADO_ID) REFERENCES SEL_NUM_DADO (NUM_DADO_ID);


ALTER TABLE OBJETO ADD CONSTRAINT Relationship4 FOREIGN KEY (PERSONAJE_ID) REFERENCES PERSONAJE (PERSONAJE_ID);


ALTER TABLE PERSONAJE ADD CONSTRAINT Relationship5 FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID);
