USE DNCONTROL;

START TRANSACTION;

-- Inserciones en tabla SEL_NUM_DADO
INSERT INTO SEL_NUM_DADO (NUM_DADO) VALUES (2);
INSERT INTO SEL_NUM_DADO (NUM_DADO) VALUES (4);
INSERT INTO SEL_NUM_DADO (NUM_DADO) VALUES (6);
INSERT INTO SEL_NUM_DADO (NUM_DADO) VALUES (8);
INSERT INTO SEL_NUM_DADO (NUM_DADO) VALUES (10);
INSERT INTO SEL_NUM_DADO (NUM_DADO) VALUES (12);
INSERT INTO SEL_NUM_DADO (NUM_DADO) VALUES (20);
INSERT INTO SEL_NUM_DADO (NUM_DADO) VALUES (100);
-- Fin inserciones en tabla SEL_NIM_DADO

-- Insercion usuarios
INSERT INTO USUARIO (EMAIL, NOMBRE_USUARIO, PASSWD, DM) VALUES
('admin@gmail.com', 'admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', true);
-- Fin usuarios

-- Insertar Personajes
INSERT INTO PERSONAJE (USUARIO_ID, NOMBRE_PERSONAJE, APELLIDO, TRANSFONDO, FUERZA, DESTREZA, CONSTITUCION, INTELIGENCIA, SABIDURIA, CARISMA, JUGADOR) VALUES
(1, 'Personaje 1', NULL, 'Transfondo', 16, 13, 12, 6, 6, 9, 'j');
INSERT INTO PERSONAJE (USUARIO_ID, NOMBRE_PERSONAJE, APELLIDO, TRANSFONDO, FUERZA, DESTREZA, CONSTITUCION, INTELIGENCIA, SABIDURIA, CARISMA, JUGADOR) VALUES
(1, 'Personaje 2', NULL, 'Transfondo', 6, 8, 7, 17, 15, 12, 'j');
INSERT INTO PERSONAJE (USUARIO_ID, NOMBRE_PERSONAJE, APELLIDO, TRANSFONDO, FUERZA, DESTREZA, CONSTITUCION, INTELIGENCIA, SABIDURIA, CARISMA, JUGADOR) VALUES
(NULL, 'Enemigo 1', NULL, 'Transfondo', 10, 10, 10, 10, 10, 10, 'e');
INSERT INTO PERSONAJE (USUARIO_ID, NOMBRE_PERSONAJE, APELLIDO, TRANSFONDO, FUERZA, DESTREZA, CONSTITUCION, INTELIGENCIA, SABIDURIA, CARISMA, JUGADOR) VALUES
(1, 'Personaje 3', NULL, 'Transfondo', 20, 20, 20, 20, 20, 20, 'j');
INSERT INTO PERSONAJE (USUARIO_ID, NOMBRE_PERSONAJE, APELLIDO, TRANSFONDO, FUERZA, DESTREZA, CONSTITUCION, INTELIGENCIA, SABIDURIA, CARISMA, JUGADOR) VALUES
(NULL, 'Enemigo 2', NULL, 'Transfondo', 30, 15, 50, 25, 40, 10, 'e');
-- Fin personajes

-- Insertar Objetos
INSERT INTO OBJETO (PERSONAJE_ID, NOMBRE_OBJETO, DESCRIPCION, VALOR) VALUES
(1, 'Pesos balanza', 'Un set de pesos para valanza sin apenas valor', 4);
INSERT INTO OBJETO (PERSONAJE_ID, NOMBRE_OBJETO, DESCRIPCION, VALOR) VALUES
(2, 'Cristales de ragn', 'Piedras de alto valor entre colecionistas', 627);
INSERT INTO OBJETO (PERSONAJE_ID, NOMBRE_OBJETO, DESCRIPCION, VALOR) VALUES
(3, 'Monedas', 'Dinero', 43);

INSERT INTO OBJETO (PERSONAJE_ID, NOMBRE_OBJETO, DESCRIPCION, VALOR) VALUES
(4, 'Pesos balanza', 'Un set de pesos para valanza sin apenas valor', 4);
INSERT INTO OBJETO (PERSONAJE_ID, NOMBRE_OBJETO, DESCRIPCION, VALOR) VALUES
(5, 'Cristales de ragn', 'Piedras de alto valor entre colecionistas', 627);
INSERT INTO OBJETO (PERSONAJE_ID, NOMBRE_OBJETO, DESCRIPCION, VALOR) VALUES
(1, 'Monedas', 'Dinero', 43);
-- Fin Objetos

-- Inserccion habilidades
INSERT INTO HABILIDAD (NUM_DADO_ID, NOMBRE_HABILIDAD, DESCRIPCION, CANTIDAD_DADO) VALUES
(NULL, 'Respiracion acuatica', 'Puede respirar bajo el agua', 0);
INSERT INTO HABILIDAD (NUM_DADO_ID, NOMBRE_HABILIDAD, DESCRIPCION, CANTIDAD_DADO) VALUES
(2, 'Arco y flecha', 'Utiliza su arco y flecha, causando 3d4 + Des', 3);
INSERT INTO HABILIDAD (NUM_DADO_ID, NOMBRE_HABILIDAD, DESCRIPCION, CANTIDAD_DADO) VALUES
(3, 'Aliento de fuego', 'Emite un aliento de fuego que causa 6d6', 6);
-- Fin habilidades

-- Insertar PERSONAJE_HABILIDAD
INSERT INTO PERSONAJE_HABILIDAD (PERSONAJE_ID, HABILIDAD_ID) VALUES (1, 3);
INSERT INTO PERSONAJE_HABILIDAD (PERSONAJE_ID, HABILIDAD_ID) VALUES (2, 1);
INSERT INTO PERSONAJE_HABILIDAD (PERSONAJE_ID, HABILIDAD_ID) VALUES (3, 2);
INSERT INTO PERSONAJE_HABILIDAD (PERSONAJE_ID, HABILIDAD_ID) VALUES (4, 2);
INSERT INTO PERSONAJE_HABILIDAD (PERSONAJE_ID, HABILIDAD_ID) VALUES (5, 1);
INSERT INTO PERSONAJE_HABILIDAD (PERSONAJE_ID, HABILIDAD_ID) VALUES (5, 3);
-- Fin PERSONAJE_HABILIDAD

COMMIT;
